# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::031342435657:role/terraform-eks-demo-node
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::031342435657:role/EKS-cluster-worker-node-role
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-18T02:19:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "856"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c3763f1f-d7a1-4188-9af7-b2840baa86a8
