version: 0.2
phases:
  pre_build:
    commands:
      - cd zen-terraform
      - pwd
      - terraform init
      - terraform validate
  
  build:
    commands:
      - pwd
      - ls
#      - terraform apply --auto-approve
